apiVersion: v1
kind: Service
metadata:
  name: {{ include "umbrella-test.fullname" . }}
  labels:
    {{- include "umbrella-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8101
      name: http
  selector:
    app: {{ include "umbrella-test.fullname" . }}
    {{- include "umbrella-test.selectorLabels" . | nindent 4 }}
