apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    {{- include "eureka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8761
      name: http
  selector:
    {{- include "eureka.selectorLabels" . | nindent 4 }}
